//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::KINEMATION.KAnimationCore.Runtime.Rig.KRigElementChain))]
	public class PropertyProvider_KINEMATION_KAnimationCore_Runtime_Rig_KRigElementChain : Unity.VisualScripting.SerializedPropertyProvider<KINEMATION.KAnimationCore.Runtime.Rig.KRigElementChain>
	{
	}
}
